### ISSUE TITLE
Welcome to Study Groups!

### ISSUE THREAD

**Issue by auremoser** [AberdeenStudyGroup/studyGroup#1]
Hello @FrancescaMancini  !

Thanks for your interest in the [Mozilla Science Lab](https://science.mozilla.org/), it's great to hear you're building a [Study Group](https://github.com/mozillascience/studygroup).

My name is [Aurelia](https://mozillascience.org/u/auremoser) and I work at the Mozilla Science Lab, a group building projects/programs globally to support open research and citizen science, including the Study Groups project. Just wanted to introduce myself as a resource, and answer any questions you might have.

Feel free to:
* review our new [Study Group Orientation Guide](https://mozillascience.github.io/study-group-orientation/) developed by @zee-moz , another great resource and contact available to you
* [sign up](https://docs.google.com/a/mozillafoundation.org/forms/d/e/1FAIpQLSdtKqAMQnKri-0xLx4hD_fpb000n9czsQd4oo9B2JUgtuIVlg/viewform?c=0&w=1) for our Orientation in January, where we mentor you through the early development of your Study Group
* build out [a site for your Study Group](https://github.com/mozillascience/studyGroup) and cull from our [library of lessons](https://github.com/mozillascience/studyGroupLessons) for early sessions
* join our monthly study group call (first Fridays, 11AM EST), [subscribe to our mailing list to be notified of those calls](https://mail.mozilla.org/listinfo/msl-study-groups)
* follow our #mozstudy hashtag on twitter, or [our list](https://twitter.com/MozillaScience/lists/mozstudy), ping [@auremoser](https://twitter.com/MozillaScience) to be added

**Join us on our next [Study Group Learning call](https://public.etherpad-mozilla.org/p/mozilla-studygroup-leads-january-2016), Friday January 6th, 11am EST**.

Email me at [aurelia@mozillafoundation.org](mailto:aurelia@mozillafoundation.org) with questions, or contact/social media information to join our twitter community and Study Group email listserv. Would love to learn about your lessons, challenges, topic of interest, and events. 

Thanks for reading!

Aurelia
Mozilla Science Lab
[@MozillaScience](https://twitter.com/mozillascience)

**Comment by FrancescaMancini** [comment]
Hi @auremoser,

Thanks for this. I transfered this repo to an organisation account so that it will be easier to work together with some of my collegues here in Aberdeen. 
I also signed up for the Orientation in January.
Thank you again for all the support.

Francesca
