### ISSUE TITLE
Hacky Hour!

### ISSUE THREAD

**Issue by FrancescaMancini** [AberdeenStudyGroup/studyGroup#5]
- **What is it about?**
The Hacky Hours to launch our Aberdeen Study Group is happening soon!

- **When and where is it happening?**
We will meet on Friday the 3rd of March around 4 pm at the [Bobbin](https://www.google.co.uk/maps/place/The+Bobbin/@57.1625162,-2.0984527,17z/data=!3m1!4b1!4m5!3m4!1s0x48840e11e3e5ee59:0x300bff203c3e9c60!8m2!3d57.1625162!4d-2.096264). We will be upstairs in the area on your left (we will probably be wearing some ridiculous hats so you will see us!)

- **What should you do to prepare?**
Nothing. Just come along for a drink, meet new people and tell us your opinion to make the study group work for you.

![photo](https://cloud.githubusercontent.com/assets/20244243/22892608/1c77a720-f20b-11e6-93c4-5f1d83a3a804.jpg)

**Comment by purplewakanda** [comment]
How long do you guys plan to be there?

**Comment by FrancescaMancini** [comment]
Definitely until 6, but a few of us will probably stay for longer.

**Comment by purplewakanda** [comment]
Thank you!
