### ISSUE TITLE
Suggestions from Hacky Hour

### ISSUE THREAD

**Issue by FrancescaMancini** [AberdeenStudyGroup/studyGroup#6]
This is a list of suggestions for tutorials and material for the Study Group that were discussed during the Hacky Hour on Friday the 3rd of March.

- MATLAB  tutorial

- NetLogo tutorial

- R markdown tutorial

- Code translations

- Create a collection of small walk-thorughs of a piece of code in the repo 

We also discussed when the next meetings should be and the preferred day and time seemed to be Wednesday afternoon at 5 pm.

Comment on this issue if you have any other suggestions.

**Comment by SophieS9** [comment]
Thanks for organising Friday, Francesca. It was a good event!

I mentioned it to a few people but I don't think it got written down anywhere - it might be nice to have a session on markdown. This is something I've found really helpful in R and it's applicable to other things like github as well.

**Comment by FrancescaMancini** [comment]
That's a great idea! I'll add it to the list.
